services:
  executor:
    image: execution_unit
    build: .
    volumes:
      - /bata:/bata
      - /bata/src/cleanCopy/components/execution:/app  
    restart: always

#docker run -it execution_group -v /bata:/bata -v /bata/src/cleanCopy/components/execution:/app 
