# Use an official Python runtime as a parent image
#FROM python:alpine

FROM jjanzic/docker-python3-opencv:latest

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /app

# Copy the dependencies file to the working directory
COPY requirements.txt /app/

# Install any dependencies
# no need to add open-cv
RUN pip install --no-cache-dir -r requirements.txt

# Copy the content of the local src directory to the working directory
COPY . /app/

EXPOSE 8080
# Run gunicorn when the container starts
CMD ["python", "image_processing.py"]
