FROM node:alpine as builder
#building 
WORKDIR /app
COPY package*.json .
RUN npm install
COPY . .
#build the application
RUN ["npm", "run", "build"]


#install nginx
FROM nginx:alpine
#remove files in html dir
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*

#add your own build
COPY --from=builder /app/build .

ENTRYPOINT [ "nginx", "-g", "daemon off;"]
